{% set version = "0.4.1" %}

package:
  name: vale-styles-joblint
  version: {{ version }}

source:
  - folder: Joblint
    fn: vale-Joblint-0.4.1.zip
    url: https://github.com/errata-ai/Joblint/releases/download/v{{ version }}/Joblint.zip
    sha256: a4322a76582dff1017a7d0965e6c50aacb5df95b28f0f31616ed09d41b1581e5
  - fn: LICENSE-vale-Joblint-0.4.1
    url: https://raw.githubusercontent.com/errata-ai/Joblint/v{{ version }}/LICENSE
    sha256: b9bb0975e308708b97e4a30c7665c815fe4bd3a1de2ed04d35c0eef03d4eaa69

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/Joblint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Joblint rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
